### ISSUE TITLE
Problemas para realizar migración

### ISSUE THREAD

**Issue by mfocqueteau** [IIC2513-2020-2/syllabus#10]
Hola, cuando trato de hacer las migraciones con `yarn sequelize db:migrate` me aparece este error:

```
File: .gitkeep does not match pattern: /\.js$/

ERROR: permission denied for table SequelizeMeta

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
El único cambio que he hecho al template ha sido en `database.js`, donde cambié el nombre de usuario, database y clave (según lo que creé en psql).

**Comment by meretamal** [comment]
Hola 😁 

El usuario que creaste es dueño o tiene permisos en la db que estás usando?

**Comment by franciscafdez** [comment]
Hola!
A mi igual me tira error al hacer la migración :
`"...\node_modules\.bin\sequelize" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
no me reconoce el comando sequelize y no sé porqué :(

**Comment by meretamal** [comment]
Hola @franciscafdez 😁 

Puedes intentar correr `yarn install` y luego correr las migraciones?

**Comment by franciscafdez** [comment]
@meretamal lo intenté :cry: pero ahora me tira error haciendo yarn install:
![image](https://user-images.githubusercontent.com/37311902/94322323-9897fa80-ff68-11ea-8751-a8db2f4f8c63.png)
(yarn start y yarn dev me funcionan bien)

**Comment by meretamal** [comment]
¿Estás usando Windows?

**Comment by franciscafdez** [comment]
Si 😟 😰

**Comment by meretamal** [comment]
Podrías intentar:
1. Correr el cmd como administrador
2. Borrar node_modules
3. Correr `yarn install`

?

**Comment by franciscafdez** [comment]
Con eso me funcionó, muchas graciasss!!
