### ISSUE TITLE
Problema carpeta node_modules

### ISSUE THREAD

**Issue by Brocoleta** [IIC2513-2020-2/syllabus#11]
Hola, mi grupo esta teniendo un problema con la carpeta node_modules, la persona que subió la app a github le funciona perfecto, pero a todos los otros nos sale el siguiente error al tratar de correr la aplicación:
`/mnt/c/Users/Acer/desktop/grupo-dadainc/node_modules/.bin/nodemon: 1: ../nodemon/bin/nodemon.js: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
Por lo que me he dado cuenta en la carpeta .bin los archivos no salen como un código como debiera ser, sino como un path, por ejemplo el archivo nodemon sale así:
`../nodemon/bin/nodemon.js`
He tratado con npm install y npm install --force pero ninguno de los dos funciona.

**Comment by meretamal** [comment]
Hola 😁 

Por favor intenta borrar node_moules y luego correr `yarn install`.

OJO: agreguen node_modules a su gitignore

**Comment by Brocoleta** [comment]
Ahi me funciono, gracias!
