### ISSUE TITLE
Direnv no lee archivo .envrc

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2513-2020-2/syllabus#12]
Hola, estoy configurando mi base de datos, con direnv, pero al momento de correr el comando `direnv allow .` este no retorna nada, y no carga las variables de entorno que defino. Que podré estar haciendo mal?

**Comment by meretamal** [comment]
Hola 😁 !!

Con direnv no me manejo mucho 🙈 , pero en la issue #8 puedes encontrar una posible solución y un método alternativo para setear tus variables de entorno.

Dime cómo te va 😉

**Comment by vchadwick** [comment]
@tomasalvarez13 estas en Mac o no?
Yo tenia el mismo problema, primero lo instale con brew:
$ brew install direnv
Y después en internet salía que había que correr esto:
$ echo 'eval "$(direnv hook zsh)"' >> $HOME/.zshrc
Cierra y vuelve a abrir el terminal.
Ojalá te sirva

**Comment by tomasalvarez13** [comment]
Muchas gracias! Al final lo solucioné siguiendo un tutorial para instalar direnv en ubuntu [https://www.willandskill.se/en/install-direnv-on-ubuntu](url)
