### ISSUE TITLE
Git branch no muestra todas las ramas

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2513-2020-2/syllabus#13]
Hola,
En mi terminal cuando escribo `git branch` no me muestra todas las ramas. Solo sale que puedo trabajar en la master. ¿Como arreglo esto?
Gracias!

**Comment by meretamal** [comment]
Hola 😁 !!

Puedes correr `git branch -a` y te debería mostrar todas las ramas que tienes en _origin_. Luego puedes cambiarte a estas con `git checkout {remotes/origin/nombre de la rama}`. Por ejemplo, si tu rama se llama _dev_, ejecutas `git checkout remotes/origin/dev`.

En el caso que no te deje (o no quieras estar escribiendo "remotes/origin/"), primero crea la rama localmente con `git checkout -b {nombre de tu rama}` y luego ejecutas `git pull origin {nombre de tu rama}`. Siguiendo el mismo ejemplo, sería `git checkout -b dev` y luego `git pull origin dev`

Dime si te funciona 😉

**Comment by dpvillarroel** [comment]
Si perfecto! Muchas gracias :)
