### ISSUE TITLE
Problema conexión Base de datos

### ISSUE THREAD

**Issue by martinrtc** [IIC2513-2020-2/syllabus#14]
Hola, estamos teniendo problemas al correr el programa ya que nos el error: 
parent: error: database "dbmark-z_dev" does not exist
adjunto fotos para mejor comprensión.
<img width="217" alt="Captura de Pantalla 2020-09-28 a la(s) 20 52 07" src="https://user-images.githubusercontent.com/53836754/94497076-7999a280-01cc-11eb-8c41-8b08a1f82770.png">
<img width="669" alt="Captura de Pantalla 2020-09-28 a la(s) 20 52 21" src="https://user-images.githubusercontent.com/53836754/94497087-83bba100-01cc-11eb-8e70-9e9820efcd23.png">

**Comment by meretamal** [comment]
Hola 😁 

Eso significa que no existe localmente una base de datos llamada **dbmark-z_dev**.

Según lo que veo, tienen que esa opción se use cuando no se encuentra una variable de entorno con el nombre de **DB_NAME**. Por lo tanto:

* Si es que lo quieren es utilizar una base de datos con el nombre **dbmark-z_dev**, primero asegúrense de crearla.
* Si es que lo que quieren es utilizar una base de datos distinta que ya crearon, el problema puede estar en que no están definiendo esta variable de entorno, o no se está leyendo bien.

Por favor confírmame cuál de las dos opciones están intentando seguir.

**Comment by martinrtc** [comment]
Hola!, nosotros creamos la base de datos directamente en el pgaAdmin, pero
al tratar de conectarla desde el código estamos teniendo problemas, no
sabemos cómo exactamente conectarla. Pero la base dbmark-z_dev
efectivamente está creada.

**Comment by dhvasquez** [comment]
Hola, una pregunta ¿saben en que puerto esta corriendo su base de datos de postgres?

**Comment by martinrtc** [comment]
5432

**Comment by dhvasquez** [comment]
Y en donde estan corriendo su servicio de postgres?

**Comment by martinrtc** [comment]
Estamos usando pgAdmin siesque  a eso te refieres

**Comment by dhvasquez** [comment]
No, me refiero a donde estan corriendo el servicio mismo de postgres
