### ISSUE TITLE
TypeError: Cannot read property 'findByPk' of undefined

### ISSUE THREAD

**Issue by jjzapatai** [IIC2513-2020-2/syllabus#15]
Hola, estoy teniendo un TypeError. He hecho cosas de otras issues que encontre en Internet pero no puedo solucionarlo. Alguna idea? (Al usar findAll no tengo problemas)
Así esta la ruta: 
router.param('id', async (id, ctx, next) => {
    const sala = await ctx.orm.sala.findByPk(id);
    if (!sala) ctx.throw(404);
    ctx.state.sala = sala;
    return next();
});

**Comment by meretamal** [comment]
Hola 😁 

Podrías revisar que tu modelo efectivamente se llame así? Si es que tiene alguna mayúscula si importa 🙈

**Comment by sivicencio** [comment]
@jjzapatai Puedes también verificar la versión de Sequelize que tienes instalada en tu proyecto. `findByPk` fue introducido en la versión 5. Antes de eso se usaba `findById` para lo mismo.

**Comment by sivicencio** [comment]
Viendo mejor el error, `ctx.orm.sala` es `undefined`, así que debe ser lo que dice @meretamal.

**Comment by jjzapatai** [comment]
@meretamal @sivicencio era un error del nombre del modulo! gracias!
