### ISSUE TITLE
Heroku no conecta archivo CSS

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2513-2020-2/syllabus#16]
Hola,

Hice el HTML de mi landing page y su CSS respectivo, el cual se visualiza perfectamente en mi localhost; pero al momento de hacer deploy a mi [servidor en Heroku](https://secure-crag-36666.herokuapp.com/) no hay CCS `mystyle.css`, aunque si el HTML nuevo `home.html.ejs` y se importan mis imagenes .SVG que tambien usan assetPath y estan importadas en `asset.js`

![borrar](https://user-images.githubusercontent.com/48324666/94506202-31d24580-01e3-11eb-80e2-40b545a7bd63.png)
(Se debería ver así)
Muchas gracias!

**Comment by meretamal** [comment]
Hola 😁 

Primero que todo, para que entiendan un poco mejor como funcionan las hojas de estilo en el _template_, la idea es importar todas estas en su archivo **index.scss**. Esto significa que todas sus vistas van a compartir un mismo estilo, para que tengan ojo en cuanto a cómo van declarando estos (como dato, Ruby on Rails también hace esto 💎 ).

Ahora, en producción pasa que se minimiza este archivo (**index.scss**) en uno llamado **app.css** y, al revisar su código, me di cuenta que en **layout.html.ejs** les falta lo siguiente:
```html
<% if (env !== 'development') { %>
  <link rel="stylesheet" href="<%= assetPath('app.css') %>" />
<% } %>
```

lo cual importa **app.css** cuando están en su ambiente de producción.

Arreglando estas cosas deberían poder cargar su css sin problemas en Heroku.

Cuéntame cómo te va 😉
