### ISSUE TITLE
validación unique en Sequelize 

### ISSUE THREAD

**Issue by mimunoz11** [IIC2513-2020-2/syllabus#17]
Hola,

Armando validaciones para nuestra app nos encontramos con un error para validar la unicidad en el mail de usuarios.

Buscamos en internet y el problema no esta documentado.

Adjunto parte de nuestra validación:

`email: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        notEmpty: true,
        isEmail: true,
      },
      unique: true,
    }`

El resto de las validaciones funciona bien. Quedamos atentos, gracias!

**Comment by meretamal** [comment]
Hola 😁 

Si no equivoco, el tema de la unicidad de una columna la deben manejar a nivel de base de datos, es decir, esta debe venir como un _constraint_ y no como una validación. Más info de esto [acá](https://sequelize.org/master/manual/validations-and-constraints.html).

Por lo tanto, lo que deben hacer es crear una migración de tipo `addConstraint` que lo agregue a la columna `email` de su tabla ([acá](https://sequelize.org/master/class/lib/dialects/abstract/query-interface.js~QueryInterface.html) pueden ver cómo hacerlo)
