### ISSUE TITLE
Problema ctx.orm.<nombre>.findAll(): relation does not exist

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2513-2020-2/syllabus#18]
Hola! 
Al tratar de correr:
` const mascotas = await ctx.orm.mascota.findAll();`
Para la ruta index de "mascotas" tengo el siguiente error (están ocultos los atributos del modelo en la captura de pantalla)

![Screen Shot 2020-09-29 at 12 22 53](https://user-images.githubusercontent.com/42187498/94579004-b9a16980-024e-11eb-81b0-39c8125ac9e2.png)

Y se que es por que esta buscando en la tabla "mascota" en lugar de la tabla "mascota**S**" (plural) pero no entiendo por que. Cuando ejecuto el mismo comando con "usuario" busca en la tabla "usuarios" como debería ser. A que se puede deber esto? Gracias!

**Comment by meretamal** [comment]
Hola 😁 

Puedes revisar si te faltan migraciones por ejecutar?

**Comment by kelseyfranken** [comment]
como puedo revisar eso?

**Comment by meretamal** [comment]
Si ejecutas `yarn sequelize db:migrate` se deberían ejecutar las migraciones faltantes.

**Comment by kelseyfranken** [comment]
No tenía migraciones faltantes. Me salió: No migrations were executed, database schema was already up to date. :(

**Comment by kelseyfranken** [comment]
voy a cambiar el nombre de la tabla a ingles :)

**Comment by meretamal** [comment]
Ojo que también vas a tener que modificar manualmente el modelo 🙈 

Cuéntame cómo te va 😉

**Comment by kelseyfranken** [comment]
me funcionó!! muchas gracias 😸 !
