### ISSUE TITLE
Permiso para usar mdl

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#2]
Hola! 
Me preguntaba si se puede usar mdl (https://getmdl.io/index.html) en el proyecto.
Gracias

**Comment by meretamal** [comment]
Hola 😁 

No se puede utilizar 🙈 . De todos modos, si puedes ver su código fuente y tomarlo como inspiración.

**Comment by sivicencio** [comment]
@ChayoPerez Tal como dice @meretamal, no vamos a permitir utilizarlo. La razón detrás es que parte del curso es aprender a estilar HTML con CSS, tanto en layout como en componentes. Material Design te entrega todas estas herramientas, entonces se perdería ese objetivo.

Entiendo que puede parecer "innecesario" el esfuerzo, pero valdrá la pena a futuro cuando quieran sobreescribir estilos de librerías existentes, o entender por qué una regla CSS no se está aplicando correctamente.
