### ISSUE TITLE
password authentication failed

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2513-2020-2/syllabus#20]
Estaba trabajando de sin problemas, de repente se fue al diablo y ahora no puedo iniciar la app.
Se me falla al hacer yarn dev y no logro solucionarlo.
![image](https://user-images.githubusercontent.com/48532824/94731960-f9924a80-033b-11eb-9472-f10b1414ba06.png)

**Comment by meretamal** [comment]
Hola 😁 

Puedes verificar que:
1. Tus variables DB_USERNAME, DB_PASSWORD y DB_NAME efectivamente tengan un valor guardado.
2. Que tus variables tengan las credenciales correctas.

**Comment by VicenteElCyrano** [comment]
Las verifiqué y están bien

**Comment by jjzapatai** [comment]
nose si sirva, pero con direnv me funciona corriendo esto:
eval "$(direnv hook bash)"
