### ISSUE TITLE
Forma a responder por cada uno

### ISSUE THREAD

**Issue by camaruri** [IIC2513-2020-2/syllabus#21]
Hola, no encuentro la distribución sobre que forma debe responder cada uno.
Gracias

**Comment by meretamal** [comment]
Hola 😁 

Se mandó en anuncio. [Acá](https://docs.google.com/spreadsheets/d/1I9YzX10SyNNyPOcPcil-RN9XT9GBDh8sR_bWEsCqOl8/edit?usp=sharing) puedes acceder a la planilla con la distribución de las formas.
