### ISSUE TITLE
[Forma 3][Pregunta 1] Muertes por región

### ISSUE THREAD

**Issue by jcechavarri** [IIC2513-2020-2/syllabus#22]
Hola! 

Cuando nos piden devolver un array con las muertes por región, debemos dejar las filas con "Total" o debemos filtrarlas?

Gracias

**Comment by sivicencio** [comment]
@jcechavarri Para poder responderte mejor, ¿a qué función específica de las 4 te refieres?

**Comment by jcechavarri** [comment]
> @jcechavarri Para poder responderte mejor, ¿a qué función específica de las 4 te refieres?

A la 2!

**Comment by sivicencio** [comment]
@jcechavarri Puedes dejar las filas con "Total". Queda a criterio tuyo.
