### ISSUE TITLE
[pregunta 1][forma 2] Formato strings en pcr.json

### ISSUE THREAD

**Issue by mimunoz11** [IIC2513-2020-2/syllabus#24]
Hola, al imprimir los datos de pcr.json los datos Region y Codigo_region vienen con comillas extras por ejemplo:

`Region: '"Los_Lagos"'` 
en vez de:
`Region: 'Los_Lagos'`

Mi duda es: ¿Debemos ignorar esas comillas extras o da igual? Lo pregunto porque al momento de asignarlo como llaves o values en nuestras respuestas estoy repitiendo el formato con el que vienen.

Saludos,

**Comment by sivicencio** [comment]
@mimunoz11 Puedes dejar las comillas tal como vienen. No debería afectar en la construcción de las keys. Si encuentras un error con esto, avísanos por favor.
