### ISSUE TITLE
[Forma 3][Pregunta 3]

### ISSUE THREAD

**Issue by jcechavarri** [IIC2513-2020-2/syllabus#26]
Hola!

Mirando el objeto `postsResponses` veo que para un mismo código hay muchos post. No me queda claro cual tiene que ser el formato para mostrarlos. Por ejemplo, puedo asumir que todos los post con el mismo código tendrán el mismo valor de `Content-encoding` y `Expect-ct` para luego mostrar cada post?

Algo tipo:

```
Headers
  - Content-encoding: gzip
  - Expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

Body

Titulo1
postbody1

Titulo2
postbody2

Titulo3
postbody3
```

Que del ejemplo no me queda claro si los headers son los mismos para un código.

Graciass

**Comment by jcechavarri** [comment]
> Si te fijas en el ejemplo, hay una sección que parte con `OK (200)` y luego otra que parte con `Not Modified (304)`. Eso te marca el inicio de un nuevo response.


@sivicencio No me queda clara una cosa, entonces podría haber más de una seccion con `OK (200)` ?

**Comment by sivicencio** [comment]
Claro, es una lista de responses, y podría haber varios con status 200, así que sí, verás cosas un tanto repetidas.
