### ISSUE TITLE
[Forma 1] [Pregunta 1]

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2513-2020-2/syllabus#29]
Hola, tengo la duda de si en las funciones 2 y 3 tengo que considerar solo los casos del día más reciente o si es de todos los días?

Gracias de antemano :smile:

**Comment by sivicencio** [comment]
Hola. Son todos los días. Sólo la primera función involucra el día más reciente explícitamente.

**Comment by Dnpoblete** [comment]
Muchas gracias por la respuesta, pero entonces en la función 3, habría que buscar el mayor numero de casos, independientemente del día o la región, por ejemplo, podría ser una región X de hace 2 días?

**Comment by sivicencio** [comment]
En este set de datos no sería posible, porque como son acumulados, el número de casos del día más reciente será `>=` al de los días anteriores. Sin embargo, para la función 3 debiesen encontrar el valor en base a `Casos_acumulados`, no a la fecha.
