### ISSUE TITLE
Paquetes y librerías permitidas

### ISSUE THREAD

**Issue by meretamal** [IIC2513-2020-2/syllabus#3]
Si quieres consultar por algún paquete o librería que podrías utilizar en el proyecto, deja un comentario con el nombre junto con la razón por la cual quieres utilizarla y se te indicará en la brevedad si está o no permitida 😁 .

**Comment by bmurtagh01** [comment]
koa-session | Para el manejo de sesiones en Koa

**Comment by meretamal** [comment]
Hola @bmurtagh01 😁 .

Si, lo puedes utilizar. Es más, ya viene incluido en el _template_.

**Comment by bmurtagh01** [comment]
Sisi acabo de cachar, pero ¿saben donde hay buena documentación o ejemplos? Que hasta ahora lo único que he encontrado es el ejemplos básicos como el de su respositorio en Github y no tengo idea como aplicarlo a mi aplicación que es mucho más complejo.

**Comment by Seba-vp** [comment]
Hola, para almacenar imágenes en s3 encontré un tutorial donde usan aws-sdk y archiver, están permitidas esas librerías?

**Comment by meretamal** [comment]
Hola @Seba-vp, puedes usarlos 😁

**Comment by Deleon20** [comment]
Hola! se puede usar la libreria Yup para las validaciones con Formik?

**Comment by sivicencio** [comment]
@Deleon20 Sí, pueden utilizarla 😉

**Comment by MaximilianoVergara** [comment]
Hola se puede utilizar el componente  react-tournament-bracket,https://github.com/moodysalem/react-tournament-bracket

**Comment by meretamal** [comment]
@MaximilianoVergara, si puedes utilizarla 😁

**Comment by gachondoj** [comment]
Hola, se puede usar react-router?

**Comment by VicenteElCyrano** [comment]
Hola, se puede utilizar express?

**Comment by sivicencio** [comment]
@VicenteElCyrano El proyecto está basado en koa. No me queda claro por qué necesitarías express. ¿Podrías justificar tu caso, por favor?

**Comment by VicenteElCyrano** [comment]
@sivicencio por nada en especial, simplemente estaba investigando en internet como crear una api y en muchas partes utilizaban express, entonces antes de meterme a investigar quería saber si se podia usar.

**Comment by meretamal** [comment]
Hola @VicenteElCyrano 😁 

Tanto Koa como Express son _frameworks_ que nos proporcionan un conjunto de herramientas para poder desarrollar servidores web.

El _template_ del curso utiliza Koa y la idea es que ocupes este mismo para desarrollar tu API (tal como dice en el README del proyecto,**"La aplicación debe desarrollarse en Node.js y koa."**).

Puedes encontrar material suficiente en la [cápsula 14](https://github.com/IIC2513-2020-2/syllabus/blob/master/capsulas/capsula-14.md) y en [Savetalk](https://github.com/IIC2513-2020-2/savetalk)

**Comment by VicenteElCyrano** [comment]
@meretamal perfecto, gracias!

**Comment by faandrade** [comment]
hola! le comenté ayer al profe en clases si es que se podía usar openAPI para hacer la documentación de la api del proyecto, a lo cual me respondió que no había ningún problema.. buscando en internet encontre [este post](https://medium.com/wolox/documenting-a-nodejs-rest-api-with-openapi-3-swagger-5deee9f50420) y planeaba seguirlo para hacer la documentación pero necesita el paquete  **swagger-ui-express** para hacer el display de forma más 'elegante' .. lo puedo utilizar?

**Comment by sivicencio** [comment]
@faandrade Está bueno bueno el post para aprender a escribir un documento en formato OpenApi. Puedes seguirlo justamente para obtener el documento JSON (o YAML) con la especificación de tu API. La parte final utiliza el paquete que mencionas para crear una aplicación que muestre la API en una URL. El "problema" es que utiliza `express` como framework, y el proyecto del curso está en `koa`. Entonces veo las siguientes opciones:
- Puedes crear **otra aplicación** con express para poder visualizar la documentación de la API solamente, y que deberías por supuesto subir a Heroku. Luego en tu README o en el formato que entregues la documentación de la entrega, incluyes el link a esta nueva aplicación
- Puedes utilizar alguna librería similar a `swagger-ui-express` pero para koa. Con una búsqueda "rápida" encontré esta (pero no la probé): https://github.com/scttcper/koa2-swagger-ui#example-with-koa-router-and-yaml-source (el link va directamente a un ejemplo de cómo usarla con `koa-router`)
- Puedes utilizar el servicio [SwaggerHub](https://swagger.io/tools/swaggerhub/), que permite subir specs de una API (archivo JSON o YAML) y ellos hostean un sitio para visualizarla. Tienes que crear una cuenta y tienen una capa gratuita que debería ser suficiente para tu caso.

**Comment by faandrade** [comment]
@sivicencio Una pregunta .. según lo que entiendo, en el ejemplo de [koa2-swagger-ui](https://github.com/scttcper/koa2-swagger-ui#example-with-koa-router-and-yaml-source) la variable ***spec*** sería el JSON en el mismo formato que el que se muestra en el post que comenté anteriormente verdad?? voy a ver si me resulta con ese paquete .. también encontré uno que se llama [koa-openapi](https://www.npmjs.com/package/koa-openapi) .. se puede usar? (para tener un plan b)

**Comment by sivicencio** [comment]
@faandrade Yo diría que sí (como mencioné, no he probado la librería). Y sí, puedes usar cualquier otro paquete que haga lo mismo, es decir, que permita mostrar en una página web la documentación de la API, a partir de una especificación en OpenApi.
