### ISSUE TITLE
[forma 2][Pregunta1]

### ISSUE THREAD

**Issue by faandrade** [IIC2513-2020-2/syllabus#30]
La función 3 debe retornar el objeto que modela la región donde se hicieron menos PCR en un día en particular??

Por ejemplo si en la región X el día Y se hizo solo 1 PCR (suponiendo que este es el mínimo posible) pero en el acumulado de los días el total de PCRs hechos en la región X es mayor que de la región X2, entonces la región X no sería la con menos PCR hechos.

la pregunta es por si se espera que consideremos el total de PCRs hechos en una región a la hora de decidir cual es el mínimo, y en caso de ser así, se pide retornar un objeto de la forma { time, Total, Region }, que se debería poner en time ?

**Comment by sivicencio** [comment]
El objeto que se pide debe corresponder a la región con menos PCRs totales (acumulados), sin importar cuántos se hicieron ese día. Visto de otra forma, como son datos acumulados, el dato corresponderá también al día más antiguo que esté disponible.

**Comment by sivicencio** [comment]
@faandrade **UPDATE**: Me corrijo, estaba confundiendo los datos. Los PCRs **NO SON* acumulados. Dicho esto, lo que debes hacer es encontrar el valor mínimo de PCRs hechos, y retornar ese dato (en conjunto con el día y la región).

**Comment by faandrade** [comment]
@sivicencio  perfecto!, entonces a modo de aclaración, en el ejemplo anterior debería retornar el objeto con valores {Y, 1, X}

**Comment by sivicencio** [comment]
Sí, suponiendo que 1 es el mínimo de PCRs para alguna región en un día en particular dentro de los datos.
