### ISSUE TITLE
[Forma 1][Pregunta 1][Función 3 y 4] ("Casos_acumulados")

### ISSUE THREAD

**Issue by NicolasCastillo24** [IIC2513-2020-2/syllabus#32]
Hola! Solo quiero asegurarme que esperan que trabajemos con los Casos_acumulados, como un valor que, efectivamente, es acumulado. Es decir, a la hora de buscar el máximo, no se deben sumar unos con otros, y a la hora de sacar el promedio tampoco. Solo basta con usar el ultimo valor acumulado. 

Muchas Gracias. 

Edit: Viendo las preguntas realizadas en el zoom veo que a pesar de que sean casos acumulados esperan que los sumemos y saquemos el promedio. Me gustaría confirmar esto?

**Comment by mimunoz11** [comment]
Me entro la misma duda, yo no estaba trabajando los valores como un valor acumulado. Mi forma es la 2.

**Comment by sivicencio** [comment]
Efectivamente, aunque no tenga mucha aplicación práctica en este caso particular, lo que se busca es que calculen promedios y obtengan máximos, en base al campos `Casos_acumulados`.
