### ISSUE TITLE
Propiedad column, pregunta1 forma2

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#33]
Hola!
No sé si me pueden responder qué es la propiedad column :(
Gracias

**Comment by sivicencio** [comment]
Si exploras el objeto `covid.pcr`, verás que tiene una propiedad `columns`. Esta incluye los nombres de las columnas a las que se refieren los datos en `covid.pcr.values`.

**Comment by ChayoPerez** [comment]
Pero cual es la utilidad? Que el orden puede cambiar?

**Comment by sivicencio** [comment]
Permite procesar los datos sin importar los labels de las columnas. Podrían cambiar los nombres y los objetos que hay que construir con ciertas keys se procesarían con el nombre actualizado.

De todas formas, sólo vamos a exigir que la función 2 use los labels de `columns` como tal. Pueden suponer que el orden se mantendrá por simplicidad.
