### ISSUE TITLE
[Forma 3] [Pregunta 1 Función 1]

### ISSUE THREAD

**Issue by rodobkn** [IIC2513-2020-2/syllabus#34]
Hola!

Estuve mirando el objeto covid.deaths , con el cual hay que trabajar, y resulta que hay un array en covid.deaths.values donde la región se llama '"Total"', y que efectivamente trae todos los muertos en ese día en específico.

Mi duda es que si nosotros sumamos manualmente todos los muertos por día, sin contar esta región llamada '"Total"', nos da siempre un resultado menor en una unidad a la cantidad de muertos de '"Total"'.

Por ejemplo, si sumamos todos los muertos del dia 29 nos da -> 200
Si revisamos la región "'Total"' del día 29 nos da --------------> 201

Con cual nos quedamos? Yo no se si se habían dado cuenta que existía esa columna dentro de lo retornado en covid.deaths, porque de ser así es muy fácil esta pregunta.

**Comment by mjgarrido1** [comment]
Tengo la misma duda, yo considere la region "Total" pero efectivamente si hacemos la sumatoria manualmente entonces esa region "Total" es distinta a la suma de los valores de todas las regiones en un dia especifico.

**Comment by sivicencio** [comment]
Esta función pide que se retorne un arreglo de arreglos, que será un subconjunto del total de los datos. Para la forma 3, el criterio es que sea el total nacional, y efectivamente viene un dato que trae esa información "lista".

No tienes que sumar manualmente (aunque si lo haces, está bien igual). No había hecho el ejercicio de sumar los valores y, por lo tanto, no me había percatado de esa diferencia en una unidad. Puedes elegir la forma que más te acomode, aunque una sea más "fácil" que la otra.
