### ISSUE TITLE
[Forma 2][Pregunta 3]

### ISSUE THREAD

**Issue by matiuc** [IIC2513-2020-2/syllabus#35]
Hola, ¿como hago para obtener la información enviada desde la función render(), en mi codigo HTML?

**Comment by meretamal** [comment]
Hola 😁 

Funciona igual a como lo han hecho en el proyecto, utilizando ejs.

**Comment by camaruri** [comment]
Tengo la misma duda, como recibir la informacion que mandamos desde render en el index.html?

**Comment by sivicencio** [comment]
Tal como dijo @meretamal, es igual que en el proyecto. Ustedes pasan un objeto y lo pueden acceder desde la vista.

**Comment by camaruri** [comment]
si eso de usarlo en la vista lo entiendo, pero nose con que nombre se accede.
Si se lo tenemos que poner nosotros y pasarselo o viene con uno ya predeterminado.
No entiendo bien el paso por render, que se supone que nosotros no tenemos que tocar render.js

**Comment by sivicencio** [comment]
No tienen que quitar el llamado a `render`, y en esa línea, sólo deben modificar el parámetro que se le pasa a la función.
