### ISSUE TITLE
F2-P3 Error: Cannot find module 'ejs'

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#36]
Perdón, siento que he preguntado caleta, pero me sale este error cuando corro la pregunta 3 sin hacerle ningún cambio y con el index prácticamente vacío. Es porque me falta hacer un archivo o qué está pasando? Agradecería mucho la ayuda, si me la pueden dar :(

Pregunta 3
`const photosResponse = require('../../data/http/photos.json');
const codes = require('../../lib/http/codes');
const render = require('../../lib/render');
function renderHttpResponse() 
{ 
}
module.exports = {
  renderHttpResponse,
}`

index:
`const pregunta3 = require('./src/forma2/pregunta3');
pregunta3.renderHttpResponse();
`

**Comment by meretamal** [comment]
Hola 😁 

Ejecutaste yarn install?

**Comment by ChayoPerez** [comment]
> Hola 😁
> 
> Ejecutaste yarn install?

Me salvaste la vida, gracias!
