### ISSUE TITLE
[Forma 2][Pregunta 2]

### ISSUE THREAD

**Issue by fcartoni** [IIC2513-2020-2/syllabus#37]
Hola! No entiendo bien si cuando piden la región será siempre Kanto o cómo la obtengo?? Porque el json de pokedex no lo entiendo mucho y usando la función que nos dan "getKantoPokedex()" tampoco se entiende mucho como se organizan los datos. Gracias!

**Comment by sivicencio** [comment]
Hola. En este caso los datos sólo traen información de Kanto efectivamente, así que todos los objetos con pokémons tendrán una key `region` con este valor. Para obtenerlo tienes que mirar los datos de `getKantoPokedex()` que no correspondan a la lista de pokémons. Parte de la pregunta es identificar la key que contiene el dato.

**Comment by fcartoni** [comment]
Ahh si perfecto! Pero como Kanto es la region para todos, no se puede escribir directamente? Y para el name que también se saca de getKantoPokedex() ese si sacarlo de ahí?

**Comment by fcartoni** [comment]
O sea, el name si sacarlo identificando la key que contiene el dato

**Comment by sivicencio** [comment]
No puedes escribir el string `"Kanto"`, si a eso te refieres. Tienes que obtenerlo del objeto que retorna `getKantoPokedex()`.
