### ISSUE TITLE
[forma 1][p1][funcion 4]

### ISSUE THREAD

**Issue by mjespinoza** [IIC2513-2020-2/syllabus#38]
Se puede asumir que siempre serán 5 días en values? 
Gracias de antemano

**Comment by sivicencio** [comment]
La solución debiese funcionar con más o menos días que 5. Si tu solución necesita esta suposición, deberías re-pensarla de otra forma.

**Comment by mjespinoza** [comment]
Entonces si hay más de 5 días se deberían considerar todos o los 5 más recientes?

**Comment by sivicencio** [comment]
Todos. Si hay 10 días, se calcula `avgCases` y `maxCases` usando los 10 días.
