### ISSUE TITLE
[Forma 3][Pregunta 1][Función 4]

### ISSUE THREAD

**Issue by sgutgar** [IIC2513-2020-2/syllabus#39]
El worrying se refiere a que hubo más de 500 muertes **el día 5** supongo, ya que sino no sería acumulado.

**Comment by sivicencio** [comment]
Se refiere a si en una región en particular hay o no más de 500 muertes. Podría ya haber partido con más de 500 en el día más antiguo, en cuyo caso sería `true`. O alcanzarlo en el día 3...o en el día 5.
