### ISSUE TITLE
Duda Diagrama E-R

### ISSUE THREAD

**Issue by gachondoj** [IIC2513-2020-2/syllabus#4]
Hola, quería saber si puedo poner varias veces la misma entidad en el diagrama para que quede mas ordenado
Gracias

**Comment by sivicencio** [comment]
@gachondoj No estoy seguro de haber entendido la pregunta. ¿Podrías explicar un poco por qué poner una entidad más de una vez? O dicho de otra forma, ¿por qué una sola vez "no te sirve"?
