### ISSUE TITLE
[FORMA 1][PREGUNTA 2]

### ISSUE THREAD

**Issue by camaruri** [IIC2513-2020-2/syllabus#40]
Hola, no me queda claro el formato en el que tiene que ir la información.
dice "retorne una promesa que resuelva a un array con información de todos los ganadores de los últimos 10 años."
que lo resuelva no se si es que se imprima la informacion o si se tiene que retornar un array

**Comment by sivicencio** [comment]
Una promesa siempre resuelve a un valor cuando es exitosa (aunque ese valor sea `undefined`). En este caso está explícito que el valor es un array, y que además se debe retornar la promesa.
