### ISSUE TITLE
[forma 1] [pregunta 2]

### ISSUE THREAD

**Issue by RositaMunoz** [IIC2513-2020-2/syllabus#41]
Hola!
Estaba viendo que para algunos ganadores de premios novel no se define _surname_ o _bornCountry_, pero la promesa de ```getLaureate(id)``` si se resuelve exitosamente, dejamos esos valores como undefined o tenemos que hacerle algún cambio?

Saludos

**Comment by sivicencio** [comment]
¡Buena pregunta! Si el dato no viene, pueden incluirlo como `undefined` simplemente.

**Comment by RositaMunoz** [comment]
Perfecto! Muchas gracias profe!
