### ISSUE TITLE
[Forma 1][Pregunta 3]: ¿Es necesario incluir tags de título?

### ISSUE THREAD

**Issue by vchadwick** [IIC2513-2020-2/syllabus#43]
Hola, no me quedo claro si nos piden que incluyamos las tags de títulos (principal, secundario, etc...)

**Comment by sivicencio** [comment]
Sí, se espera que "título principal"  y "título secundario" lo mappeen a una etiqueta HTML. La decisión de cuál utilizar es parte de lo que se está evaluando.
