### ISSUE TITLE
[Forma3][Pregunta 3] ¿Preprocesar variables para la vista?

### ISSUE THREAD

**Issue by Luckbox314** [IIC2513-2020-2/syllabus#44]
Hola, ya hice la pregunta 3 pero ahora me está surgiendo al duda de si es necesario trabajar los datos que luego se le pasaran a la función render(). No es necesario pero siento que podría ser mala practica pasar cosas muy grandes en vez de varias cosas pequeñas. Tal vez estoy siendo paranoico pero se siente extraño dejar una función vacía siendo que dice /* Write your solution here */

**Comment by sivicencio** [comment]
Si consideras que necesitas pre-procesar algo, adelante. Hay bastante libertad en la solución, pero te aconsejo que no te compliques tanto. Si cumple con lo que se pide en el enunciado, está bien.

Dicho lo anterior, en este caso no estamos "cerca" de pasarle muchas cosas a la vista. Los datos son pocos realmente.
