### ISSUE TITLE
[Forma 1][Pregunta 1] Función 3

### ISSUE THREAD

**Issue by ajuanchuto** [IIC2513-2020-2/syllabus#45]
Quería saber en la función 3 si lo que me piden es encontrar la región con más casos en total, es decir, que por región tenga que sumar los casos_acumulados y luego encontrar la región con el total más alto o si es otra cosa lo que me piden. ¡Gracias! 😄

**Comment by sivicencio** [comment]
Piénsalo de la siguiente forma, no pensando en la prueba sino que en la "vida real": si te preguntan cuál es la región con más casos, y tienes datos de casos acumulados por región en distintos días, ¿qué dato deberías tomar para responder la pregunta? ¿Tiene realmente sentido sumar casos acumulados de una región?
