### ISSUE TITLE
[Pregunta 3] Import

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2513-2020-2/syllabus#46]
No cacho como se prueba esta pregunta en index, dice que la importe pero no me sale.
Utilizo: import { renderHttpResponse } from 'src/forma3/pregunta3.js';
y me sale: 
![image](https://user-images.githubusercontent.com/48532824/94870720-b0ff8d80-041e-11eb-8292-7af51c283a01.png)

**Comment by meretamal** [comment]
Hola, puedes tratar usando require?

**Comment by VicenteElCyrano** [comment]
Funcionó, muchas gracias.

**Comment by mjgarrido1** [comment]
Es necesario importar? yo no lo hice y me funciono
