### ISSUE TITLE
[P3][forma1] formato respuesta

### ISSUE THREAD

**Issue by mvaldes12** [IIC2513-2020-2/syllabus#47]
Hola!
Estoy un poco confundida con el formato, me guío más en la la parte escrita o del enunciado?
Por ejemplo, al hacer que headers y body sea una lista, en cada item me aparece un punto

Está bien?

Gracias!

**Comment by sivicencio** [comment]
Si dice "lista", deberían utilizar las etiquetas cuyo propósito sea representar una lista. El ejemplo es referencial para que tengan una idea de cómo se debería ver, pero si su implementación tiene un punto que el ejemplo referencial no, está bien igual. El ejercicio no incluye CSS, por lo que no se está evaluando la visualización, sino que usen las etiquetas adecuadas.
