### ISSUE TITLE
Entrega 1 - Diagrama ER - Contenido

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2513-2020-2/syllabus#5]
Hola, ¿qué elementos hay que incluir en el diagrama? Y, ¿qué estructura seguir? Estamos eligiendo entre los 2 diagramas adjuntados. Muchas gracias de antemano.

![image](https://user-images.githubusercontent.com/48391930/92495798-bc6bea00-f1cd-11ea-988c-a8e6e60d7c3b.png)

![image](https://user-images.githubusercontent.com/48391930/92496059-0a80ed80-f1ce-11ea-8e4e-f66a5cc8d028.png)

**Comment by dhvasquez** [comment]
Hola Diego!

Respecto a tu primera pregunta, nose bien a que te refieres con "elementos", pero lo que hay que incluir en el diagrama ER es:
1. Las entidades que van a ser guardadas en la base de datos, con sus respectivas columnas.
2. Las relaciones entre dichas entidades (casi siempre en forma de rombo), como por ejemplo "Has", "Makes", entre otros (Recordemos que estamos usando PostgreSQL, una base de datos relacional).
3. Las cardinalidades entre las relaciones, como 1 a N (1 entidad esta relacionado con N entidades), 1 a 1 estricto (una entidad esta relacionada con solo una entidad), N a N (una entidad esta relacionada con muchas otras y viceversa), etc.

En cuanto a tu segunda pregunta, en realidad hay varias formas de hacer un diagrama, y con respecto a los dos ejemplos que entregaste, ambos son correctos solo que siguen notaciones distintas, tengo entendido que el primero en general es de tipo "Chen notation" y el segundo, creo que para las relaciones utiliza "Arrow notation".

¿Cual elegir? Pues realmente cualquiera, lo importante es que sean consistentes con el tipo de notación que eligieron entre todas sus entidades, y que sea un diagrama tipo "Logical Data Model", es decir, que incluya todo lo que mencione al inicio. Para estar más seguros lo mejor sería que le pregunten directamente a su ayudante asignado.

Espero te sirva! si no, dime.
