### ISSUE TITLE
Entrega I1

### ISSUE THREAD

**Issue by mjgarrido1** [IIC2513-2020-2/syllabus#50]
al subir el zip, la carpeta comprimida se debe seguir llamando src o debo ponerle mi usuario o algo?

**Comment by VicenteElCyrano** [comment]
Cuando vas a entergar aparece el nombre que tiene que llevar.
es asi:
debe tener como nombre tu nombre, apellido y número de alumno, escritos de la siguiente manera: nombre_apellido_#alumno.zip

**Comment by sivicencio** [comment]
Para el zip es lo que dice @VicenteElCyrano, y para la carpeta que comprimes, puede seguir llamándose `src`.
