### ISSUE TITLE
Proyecto: Dudas sobre el layout

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#51]
Hola!
Tengo unas preguntas:
- Se puede hacer que una vista no use el layout?
- Se puede hacer más de un layout? Y que se pueda definir qué vista usa cual?

Gracias!

**Comment by sivicencio** [comment]
Hola. Es posible hacer las dos cosas que planteas. Puedes revisar cómo lograrlo aquí: https://github.com/koajs/ejs#layouts
