### ISSUE TITLE
assetPath a veces no funciona

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#52]
Hola! Tengo este código para pegar una imagen y mi problema es que, sin que yo cambie nada (por ejemplo cambió después de que reinicié el computador) deja de funcionar. Tengo códigos similares que tampoco funcionan a pesar de que el archivo existe en assets/images donde debería estar.

`<img src="<%= assetPath('ChefferTitulo.JPG') %>" alt="Cheffer" id="title">`

Estoy muy confundida de por qué es tan aleatorio su funcionamiento y agradecería mucho la ayuda =_= Gracias!

**Comment by sivicencio** [comment]
Hola. Me parece muy extraño lo que comentas del comportamiento aleatorio. Debería ser consistente, funcione o no funcione.

De todas formas, asegúrate de que estás agregando el asset en el archivo `src/assets/js/assets.js`. Verás cómo hacerlo con el ejemplo que aparece ahí del archivo `logo.png`. Hice una prueba en `savetalk` con una imagen que tuviese exactamente el mismo nombre que la tuya, y me funcionó. Reinicia la aplicación también, por si acaso.
