### ISSUE TITLE
Diferencias de sintaxis al crear un modelo

### ISSUE THREAD

**Issue by ftobar22** [IIC2513-2020-2/syllabus#53]
Hola!

pasa que los archivos de los modelos se me crean con un formato distinto al de las cápsulas. Quería saber si se debe a que tengo una versión distinta de algo u otra cosa.

Version de node v12.18.4
Version de yarn sequelize 6.2.0

**Capsula**
![image](https://user-images.githubusercontent.com/42159875/95530306-eaeb0980-09b3-11eb-8351-9f4136e3d2f7.png)

**Yo**
![image](https://user-images.githubusercontent.com/42159875/95530325-f63e3500-09b3-11eb-9632-ed46713b82c9.png)

**Comment by meretamal** [comment]
Hola 😁 

Esto se puede deber por el uso de distintas versiones de **sequelize-cli**

De todos modos, esta diferencia no debería tener grandes implicancias en el desarrollo de tu proyecto. Tal como dice la [documentación](https://sequelize.org/master/index.html):

> Models can be defined in two equivalent ways in Sequelize:
> 
> * Calling sequelize.define(modelName, attributes, options)
> * Extending Model and calling init(attributes, options)

por lo que finalmente va a depender de tus preferencias de sintaxis.

Si es que prefieres utilizar la primera, puedes utilizar los [comandos](https://github.com/IIC2513/generator-template/wiki/Generator-commands) del generador que se usa en el curso:
```
yo @iic2513/template:model <model name> <atributtes - name:type,[name:type]> --create
```

**Comment by sivicencio** [comment]
Efectivamente, cuando yo creé `savetalk` el último release del template del curso era del 2 de mayo, por lo tanto, utilizaba dependencias disponibles hasta esa fecha. En el caso de Sequelize como dependencia, en ese momento estaba la versión 5. 

El 12 de septiembre se hizo un nuevo release del template del curso, y varias de las dependencias que utiliza están más actualizadas ahora. En el caso particular de Sequelize y `sequelize-cli`, ya es la versión 6 (que usa esa sintaxis de clases). Probablemente `sequelize-cli` genera automáticamente la nueva sintaxis ahora.
