### ISSUE TITLE
relation (en singular) does not exist

### ISSUE THREAD

**Issue by pwillmer** [IIC2513-2020-2/syllabus#56]
Hola, no logro encontrar el error de por qué busca la tabla en singular, he seguido las capsulas tal cual en cuanto a la nomenclatura singular y plural. 

![image](https://user-images.githubusercontent.com/53840038/95928023-bd78d400-0d96-11eb-833a-6c507d2e2a00.png)

![image](https://user-images.githubusercontent.com/53840038/95927935-83a7cd80-0d96-11eb-8229-9aa9eb5d4a74.png)

**Comment by meretamal** [comment]
Hola 😁 

Para poder obtener el plural de una palabra, si no me equivoco, sequelize utiliza un paquete llamado [inflection](https://www.npmjs.com/package/inflection).

Intentando pluralizar "consulta", efectivamente termina retornando "consulta" y no "consultas". Me imagino que esto se puede deber a que estás trabajando en español, por lo que sería recomendable trabajar en inglés.

Si quieres dejarlo en español, puedes asignarle directamente una tabla a un modelo, tal como dice la documentación:

> You can simply tell Sequelize the name of the table directly as well:
> 
> ```js
> sequelize.define('User', {
>   // ... (attributes)
> }, {
>   tableName: 'Employees'
> });
> ```

**Comment by pwillmer** [comment]
Se arregló haciéndolo en inglés! . Cuál sería el comando en consola para eliminar el modelo consultas?

Gracias!

**Comment by meretamal** [comment]
Podrías eliminar el archivo **consulta.js** de tu carpeta **models**.

Para eliminar la tabla consulta, lo puedes hacer de distintas maneras:
1. Creando una migración para botar la tabla.
2. Botando tu bdd y luego borrando la migración que crea consultas y cualquier otra que interactúe con la tabla (si haces esto, todo tu grupo tendrá que botar su bdd).
3. etc
