### ISSUE TITLE
Problema "yarn add bcrypt" macOS

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2513-2020-2/syllabus#58]
Hola! Al correr el comando "yarn add bcrypt" tengo el siguiente error:
![Screen Shot 2020-10-14 at 23 25 50](https://user-images.githubusercontent.com/42187498/96069629-fc7d5700-0e74-11eb-98bb-dda429ae6738.png)
Alguna idea de como solucionarlo?
Gracias!

**Comment by sivicencio** [comment]
Hola. Intenta correr `yarn install` (o sólo `yarn`) antes de `yarn add bcrypt`. Si aún luego de eso no te funciona, comenta nuevamente esta issue y vemos cómo se puede solucionar.

**Comment by kelseyfranken** [comment]
Intente ambos y todavia tengo el mismo error :(

**Comment by kelseyfranken** [comment]
![Screen Shot 2020-10-15 at 09 36 08](https://user-images.githubusercontent.com/42187498/96124440-dcc44e00-0ec9-11eb-9b8b-e5ee3d7a8618.png)

**Comment by dhvasquez** [comment]
Hola, y si intentas borrar la carpeta "node_modules" y luego volver a realizar ```yarn install``` y luego ```yarn add bcrypt```

**Comment by kelseyfranken** [comment]
lo he intentado y tampoco me sirve :/

**Comment by kelseyfranken** [comment]
Lo probé y me arroja esto:
![Screen Shot 2020-10-15 at 12 41 43](https://user-images.githubusercontent.com/42187498/96153196-c9be7780-0ee3-11eb-90ed-a6bc07ef79e3.png)

**Comment by dhvasquez** [comment]
Y solo te ocurre al instalar bcrypt?

**Comment by kelseyfranken** [comment]
si :/ no había tenido otros problemas. Puede ser que no he actualizado macOS? tengo macOS Mojave

**Comment by kelseyfranken** [comment]
si todo bien

**Comment by sivicencio** [comment]
Hola, yo uso macOS Mojave y no tengo problemas, así que no creo que sea esa la causa.

Si probaste con `npm install` y además `yarn install`, entonces tendrás que limpiar un poco tu copia local del repo. `yarn install` genera un archivo llamado `yarn.lock`, mientras que `npm install` hace lo propio con un archivo llamado `package-lock.json`. En general uno usa `yarn` o `npm`, pero no ambas para instalar dependencias, porque sino se generan conflictos. Te sugiero entonces borrar el archivo `package-lock.json` en caso de que se haya creado y también eliminar la carpeta `node_modules`:

```bash
rm -rf package-lock.json
rm -rf node_modules
```

Luego de eso, ¿podrías verificar cuál es la versión de Node que tienes instalada? Eso lo ves con `node --version`. El template del curso funciona con las versiones 10 y 12, pero debes ser consistente en la versión que antes ya habías utilizado para instalar las dependencias. En caso de que no te aparezca una de esas dos versiones, si estás utilizando nvm, debes cambiarte a una versión compatible:

```bash
nvm use # Si tu proyecto incluye un archivo .nvmrc

# Lo siguiente son alternativas si lo de arriba no funciona
# nvm use 12 # Si no incluye archivo .nvmrc y tu proyecto usa la v12
# nvm use 10 # Si no incluye archivo .nvmrc y tu proyecto usa la v10
```

Y finalmente ejecutar de nuevo `yarn install`. Es lo que se me ocurre por ahora.

**Comment by kelseyfranken** [comment]
Al final me funcionó. Tuvo que correr: 
`yarn global add node-pre-gyp`
`yarn add bcrypt `
Gracias!! :)
