### ISSUE TITLE
Unable to connect to the database: ConnectionError

### ISSUE THREAD

**Issue by jjzapatai** [IIC2513-2020-2/syllabus#59]
Alguna idea para solucionar este error?  Unable to connect to the database: ConnectionError [SequelizeConnectionError]: password authentication failed for user "jjzapatai"

tengo el archivo .envrc creado dentro de la carpeta de la aplicación con los datos de db_username, db_password y db_name correctos. Al poner "direnv allow ." me sale ".envrc file not found "

**Comment by meretamal** [comment]
Hola 😁 

Podría ver la issue #8?

**Comment by jjzapatai** [comment]
Lo pude solucionar con esa issue! gracias.
Ahora tengo esto:
--------------------
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
--------------
tengo bien las versiones de node, nvm y  npm. corrí nvm use y tampoco sirve.

**Comment by jjzapatai** [comment]
ya lo solucione!
