### ISSUE TITLE
Error Base de datos - Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2513-2020-2/syllabus#60]
Cuando corro el comando `yarn dev` no me deja conectarme a la base de datos. Probé parando con `brew services stop postgresql` luego haciendo que parta de nuevo con `brew services start postgresql`. 

<img width="987" alt="Captura de Pantalla 2020-10-15 a la(s) 18 56 52" src="https://user-images.githubusercontent.com/53846238/96190227-42d7c200-0f18-11eb-9a6b-3dbad78e3092.png">

**Comment by meretamal** [comment]
Hola 😁 

Las credenciales de tu db que estás usando son las correctas? (nombre de la base de datos, usuario con permisos en esta, contraseña, etc)?

**Comment by dpvillarroel** [comment]
Si el problema es que no se conecta al localhost:3000 y el localhost5432 no me funciona.
