### ISSUE TITLE
[EMAIL ] Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by pwillmer** [IIC2513-2020-2/syllabus#62]
Hola! Estoy teniendo problemas para generar el mail de notificación. Siguiendo el ejemplo visto en clases, al momento de enviar aparece `internal server error` y en consola aparece lo siguiente. 

![image](https://user-images.githubusercontent.com/53840038/97646085-78f36680-1a2d-11eb-8494-afaf64b60927.png)

Buscando en internet, apareció que quizás estaba relacionado al antivirus. Lo desactivé y ahora aparece lo siguiente.

![image](https://user-images.githubusercontent.com/53840038/97646213-e2737500-1a2d-11eb-8b22-e5697d502cf1.png)

No puedo encontrar el error, ayuda

**Comment by mimunoz11** [comment]
Hola, en nuestro proyecto tuvimos un error similar al de la 2da foto. Tuvimos que verificar la cuenta en sendgrid antes de pedir la API KEY rellenando un form que te pide el mail, ciudad y otros datos.

**Comment by pwillmer** [comment]
Te pasaste Manuel! efectivamente era porque no había verificado el mail y no había rellenado ese form. Por otro lado, el primer error si es por el antivirus.  Lo desactivé y funcionó. Gracias!
