### ISSUE TITLE
Acceder a la base de datos con react

### ISSUE THREAD

**Issue by mfocqueteau** [IIC2513-2020-2/syllabus#64]
En el ejemplo de react de "photos" que ha usado el profe en las cápsulas, la variable `INITIAL_STATE` es una lista de objetos que define ahí mismo en el código. Yo quiero obtener una lista a partir de una tabla en mi base de datos. ¿Cómo lo hago?

**Comment by mimunoz11** [comment]
+1 a esta duda, lo he intendado de muchas formas sin lograrlo todavía :( .

**Comment by pwillmer** [comment]
+2

**Comment by sivicencio** [comment]
@mfocqueteau El ejemplo que mencionas utiliza un estado inicial efectivamente "estático". Si quieres obtener algo de la base de datos, necesitas crear un ruta en el backend que responda en JSON, y luego hacer un `fetch` desde la aplicación React. Puedes encontrar un ejemplo de esto en la cápsula 12.
