### ISSUE TITLE
Uso de Cloudinary con react

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2513-2020-2/syllabus#65]
Hola, Estoy tratando de hacer una vista usando react pero nose como hacerlo para poder ver las fotos con Cloudinary. Lo intenté así: `<img src={cloudinary.url(pet.imagen)}  className="item-img" ></img>`
Pero no me sale la foto y en la consola me sale el siguiente error:
![Screen Shot 2020-11-14 at 19 10 38](https://user-images.githubusercontent.com/42187498/99158028-1779fb80-26ad-11eb-835b-6ca9e4be8f40.png)
Como se pueden visualizar las imágenes con Cloudinary en react? Gracias!

**Comment by sivicencio** [comment]
Hola Kelsey,

Tendrías que incluir dentro de tu variable `pet` (que supongo que tiene información que viene como respuesta de una ruta que responde en JSON) un campo con la imagen de Cloudinary. Es decir, dentro de `ctx.body` en koa debieras incluir un objeto que incluya algo como:

```javascript
ctx.body = {
  cloudinaryImage: cloudinary.url(pet.imagen),
}
```
(Considerando que `pet` es una variable que tiene la instancia de sequelize con un pet).

Luego en React accedes directamente a `pet.cloudinaryImage`.
