### ISSUE TITLE
Deploy a Heroku - React

### ISSUE THREAD

**Issue by mimunoz11** [IIC2513-2020-2/syllabus#66]
Hola, al realizar un deploy a Heroku los componentes de react y funciones de javascript no nos funcionan, nuestra duda es ¿habrá que agregar alguna configuración extra al template?

**Comment by RositaMunoz** [comment]
Hola!
Con mi grupo tuvimos el mismo problema, en nuestro caso en el ambiente de production no estábamos importando lo necesario para que funcionara react o javascript, solo lo teníamos para development (en el header de la página).
Teníamos un ```if env != development``` sacándole eso, todo funcionó perfect.

**Comment by mimunoz11** [comment]
GRacias!
