### ISSUE TITLE
problema de rutas y renderear la vista 

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2513-2020-2/syllabus#67]
Quiero implementar la api de Youtube en mi app, para lo cual tengo el siguiente código:
![image](https://user-images.githubusercontent.com/48532824/100397193-2787c880-3027-11eb-873a-1ab488f6c936.png)
El console.log de videos funciona bien, un array con 6 elementos, pero al cargar la vista videos no tiene nada, es decir no logro enviar videos a la vista.
Estoy seguro que pasa por mi ignorancia respecto a las funciones asíncronas, pero probé varias combinaciones de código y no logro cumplir con mi objetivo. Una ayudita pls

**Comment by meretamal** [comment]
Hola 😁 

Ojo que estás mezclando manejo de promesas con `then`/`catch` y `async`/`await`.

Debería ser:
```js
const response = await function()
// lógica que utiliza response
```
o
```js
function().then((response) => {
// lógica que utiliza response
})
```
También ten en cuenta que `videos` de la línea 14 es distinto a `videos` de la linea 24 (por _scope_), por lo que a `render` le estás pasando un _array_ vacío.

**Comment by VicenteElCyrano** [comment]
Lo probaré, gracias. Y el videos de la 24 se me coló probando cosas, antes no estaba asi que nada de que preocuparse. 
![image](https://user-images.githubusercontent.com/48532824/100397752-34f28200-302a-11eb-9144-542801335ca7.png)

**Comment by VicenteElCyrano** [comment]
arreglado
