### ISSUE TITLE
[Código] Problema variable de entorno .env

### ISSUE THREAD

**Issue by EliasSabja** [IIC2513-2020-2/syllabus#68]
Hola, tengo un problema con una variable de entorno que contiene el secreto necesario para proteger las rutas con ```koa-jwt```. 
## Todas las fotos son ejemplos cortados para explicar lo que hice.
 (por si las dudas jaja)

Tengo un archivo ```.env``` con la variable.

![image](https://user-images.githubusercontent.com/48526772/100545688-d56bc080-323b-11eb-9de0-70069bbe17d0.png)
Primero se utiliza esta variable para generar el token de autenticación con la librería ```jsonwebtoken``` y funciona bien.
Se ve algo parecido a esto:

![image](https://user-images.githubusercontent.com/48526772/100546210-d18d6d80-323e-11eb-9857-f3a92cdf624f.png)
Luego se protegen las rutas, el problema es que cuando uso la misma variable de entorno, al intentar ingresar a la ruta con el token de autenticación en el header, lanza error 401 de Unauthorized.
Se ve más o menos así:

![image](https://user-images.githubusercontent.com/48526772/100546025-c128c300-323d-11eb-916a-4cf3ab61d981.png)
Pero cuando cambio ```process.env.JWT_SECRET``` por el secreto directamente sí funciona.

![image](https://user-images.githubusercontent.com/48526772/100546292-5b3d3b00-323f-11eb-92d7-a74f25cfb273.png)
El ```console.log``` retorna ```undefined``` cuando corro la aplicación, me dí cuenta que la variable de entorno del archivo ```.env``` se carga más tarde (esto haciendo ```console.log(process.env)``` en la misma línea y dentro de un middleware, en el primer caso no aparecía mi variable y en el segundo sí), tal vez por eso solo funciona dentro de un middleware, sin embargo, luego de buscar sobre esto no encontré nada. 

Si tienen alguna idea de por qué pasa esto se agradecería, ya que sino tendría que pegar el secreto directo y supongo que nos bajará en la evaluación técnica. 

Muchas gracias de antemano.

**Comment by EliasSabja** [comment]
No le agregué el label antes de crearle y parece que ahora no puedo, perdón jajaja.

**Comment by meretamal** [comment]
Hola 😁 , si es que aún no lo solucionaste, como estás usando un archivo **.env**, ¿estás usando algún paquete para poder leerlo, cómo [dotenv](https://www.npmjs.com/package/dotenv)?.

**Comment by EliasSabja** [comment]
Sí, estoy usando dotenv, en teoría está funcionando bien dado que funciona en un módulo y en el otro no.

**Comment by meretamal** [comment]
Si en ese mismo archivo corres al principio `require('dotenv').config()` no funciona?

**Comment by EliasSabja** [comment]
Graciass, ahora sí funciona aunque me parece raro que en la otra función sirva sin hacer el require. Gracias de nuevo jaja
