### ISSUE TITLE
Problemas con Sequelize para deploy en Heroku

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2513-2020-2/syllabus#7]
Hola,

Pude crear el template dado en el Wiki y correrlo sin problemas en `localhost` pero al momento de intentar hacer git push `heroku master` me lanzaba un error **master -> master (pre-receive hook declined)** y dado a que no encontraba el archivo `config/config.json` y me recomendaba eliminar del git los node_modules (los cuales según yo necesito para Sequelize). Esto no soluciono el problema, luego me indicó que tenia que inicializar el sequalize entonces corrí `yarn sequelize init` que me creo un archivo config.json pero al leerlo veo que esta seteado para mysql2 y nosotros necesitamos usar Postgres.

```remote:        ⬡ webpack: Starting Build
remote:        ⬡ webpack: Build Finished
remote:        
remote:        webpack v4.44.1
remote:        
remote:        17d023da9bb75ce401f6
remote:          size     name  module                                     status
remote:          40 B     3     multi ./js/index.js ./js/app.jsx           built
remote:          87 B     4     ./images/logo.png                          built
remote:          39 B     5     ./styles/index.scss                        built
remote:          178 B    10    ./js/index.js + 1 modules                  built
remote:          465 B    11    ./js/app.jsx + 1 modules                   built
remote:        
remote:          size     name  asset                                      status
remote:          87 B     app   app-17d023da9bb75ce401f6.css               emitted
remote:          228 B    app   app-17d023da9bb75ce401f6.css.map           emitted
remote:          131 kB   app   app-17d023da9bb75ce401f6.js                emitted
remote:          319 kB   app   app-17d023da9bb75ce401f6.js.map            emitted
remote:          6.93 kB  png   logo-dc3fc2536bddbc72213bb13245d0170e.png  emitted
remote:          293 B    json  manifest.json                              emitted
remote:        
remote:          Δt 5641ms (10 modules hidden)
remote:        
remote:        
remote:        Sequelize CLI [Node: 12.18.4, CLI: 6.2.0, ORM: 6.3.5]
remote:        
remote:        
remote: ERROR: Cannot find "/tmp/build_313742a7/config/config.json". Have you run "sequelize init"?
remote:        
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: 
remote: -----> Build failed
```
Y despues de agregar con el init el config.json

```remote:        Loaded configuration file "config/config.json".
remote:        Using environment "production".
remote:        
remote: ERROR: Please install mysql2 package manually
remote:        
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: 
remote: -----> Build failed
```
Muchas gracias por la ayuda

**Comment by meretamal** [comment]
Hola 😁 

¿Por casualidad movieron su proyecto de una carpeta a otra? Miré su repo y hay algunos archivos que les faltan que deberían en la raíz de su app.

**Comment by bmurtagh01** [comment]
Si! moví con el mouse la carpeta de la app (que estaba en Home de Ubuntu cuando la cree en el terminal) a mi carpeta de mi repositorio

**Comment by meretamal** [comment]
Buena, por favor revisa este [link](https://github.com/IIC2513/generator-template/tree/dev/generators/app/templates/base) (es del repo del generador que usan) donde podrás ver los archivos que te faltan. Entre ellos hay un archivo **.sequelizerc** que indica que el archivo de configuración es **src/config/database.js**, por lo que no se necesita un archivo **config.json**.

**Comment by bmurtagh01** [comment]
Perfecto, al final lo que hice fue crear desde 0 otra aplicación pero ahora en mi repositorio y todo Ok
Pero ahora me tira este problema


```remote:        Loaded configuration file "src/config/database.js".
remote:        Using environment "production".
remote:        
remote: ERROR: Error parsing url: undefined
remote:        
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: 
remote: -----> Build failed
```

**Comment by bmurtagh01** [comment]
Quizas tiene que ver en como definí el usuario y contraseña de mi base de datos

**Comment by meretamal** [comment]
Lo único que debería faltar sería instalar el _add-on_ de postgres en tu app de Heroku.

Esto lo puedes hacer ingresando a Heroku desde tu browser. Luego seleccionas tu app y vas a _resources_ . Esto va a agregar una variable de entorno llamada **DATABASE_URL** que usará tu app en producción.

**Comment by bmurtagh01** [comment]
Muchas gracias, funcionó perfecto :thumbsup:

**Comment by rodobkn** [comment]
> Lo único que debería faltar sería instalar el _add-on_ de postgres en tu app de Heroku.
> 
> Esto lo puedes hacer ingresando a Heroku desde tu browser. Luego seleccionas tu app y vas a _resources_ . Esto va a agregar una variable de entorno llamada **DATABASE_URL** que usará tu app en producción.
> 
> Si ya diste ingeniería de software, esto mismo se usa para el deploy, solo que Heroku lo hace automáticamente con una app de Rails

@meretamal 
Me funciono con esto, pero no se corrieron las seed. Como se realizan las seed en heroku con postgres? Puesto que en local me funciona perfecto

**Comment by meretamal** [comment]
Si ya hiciste el deploy, puedes correr `heroku run yarn sequelize db:seed:all` desde tu proyecto y van a correr las seeds en heroku.

**Comment by juakoke** [comment]
escribo heroku yarn sequelize db:migrate y me dice que no encuentra el comando  yarn para heroku alguna idea de que puedo hacer?
