### ISSUE TITLE
Pasando parámetros a React desde html

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#71]
Hola!
Tengo el siguiente problema en React en el que agradecería me pudieran ayudar. Estoy intentando pasar parámteros a mi componente desde la vista y no imprime nada.

En mi vista tengo lo siguiente:

```<div id="react-param" data-x="Loren ipsum"></div>```

En app.jsx

```
import ParamReact from './components/ParamReact';
const reactAppParamContainer = document.getElementById('react-param');

if (reactAppParamContainer) {
  ReactDOM.render(<ParamReact />, reactAppParamContainer);
}
```

Y en el componente:

```
export default function ParamApp(props) {
return (
    <div>{props.data.x}</div>
    );
}
export default hot(module)(ParamApp);
```

Si cambio el props.data por un texto plano cualquiera tampoco aparece. Solo se arregla sacando el export default (el texto, el props no se imprime nunca)
¿Alguna idea de qué puedo hacer? Es lo que entendí del video :(
Gracias!

(El programa está aqui: https://github.com/ChayoPerez/AppWebDePrueba/blob/master/src/assets/js/components/ParamReact.jsx)

**Comment by meretamal** [comment]
Hola 😁 .

Te falta pasarle un prop llamado `data` a `ParamReact`, el cual sea igual al _dataset_ de reactAppParamContainer.

Te dejo el link de [savetalk ](https://github.com/IIC2513-2020-2/savetalk/blob/master/src/assets/js/app.jsx)para que veas cómo lo hacen ahí.

**Comment by ChayoPerez** [comment]
Muchas gracias, está funcionando! :)))
