### ISSUE TITLE
Backend: No se puede acceder a este sitio

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2513-2020-2/syllabus#72]
Hola! Pregunto rápido para no morir en el examen.
Hice toda la lista de instrucciones para el backend, pero cuando intento meterme a la página de la api me sale error. En la consola por donde hago yarn dev todo sale como si todo estuviera bien. ¿Cuál podría ser el problema?

Algo que se me ocurre es que no sé como rellenar el PASSWORD en database.js porque según yo mi usuario 'postgres' no tiene contraseña, así que lo dejé en blanco ._.

Gracias!

**Comment by sivicencio** [comment]
Hola @ChayoPerez. Si no pudieras conectarte a la BD, verías un error en la consola al hacer `yarn dev` (busca en todo lo que aparece luego de ingresar ese comando). La configuración debiese ser la misma que utilizaron para el proyecto. Puedes colocar el output acá si gustas.
