### ISSUE TITLE
Problema para correr frontend (babel)

### ISSUE THREAD

**Issue by jjzapatai** [IIC2513-2020-2/syllabus#74]
Hola, necesito ayuda para probar el ejemplo del frontend. Tengo este error luego de clonar el repo y hacer yarn start:
![Captura de pantalla de 2020-12-14 01-15-59](https://user-images.githubusercontent.com/48264167/102040096-7e70fa00-3daa-11eb-98ad-f9afbfa7948f.png)

Intenté con los pasos que indican ahí, y aun así no me funciona

**Comment by meretamal** [comment]
Hola 😁 

Si te fijas, tienes una carpeta node_modules en 2020-02. Si la borras, te debería funcionar.

**Comment by jjzapatai** [comment]
ahí me funcionó, gracias!
