### ISSUE TITLE
No se actualiza la pagina en modo dev

### ISSUE THREAD

**Issue by sgutgar** [IIC2513-2020-2/syllabus#75]
Hola, no se me actualizan los cambios en modo dev,, siempre esta en este estado
[HMR] Waiting for update signal from WDS...
No se cual puede ser el problema pero cerrar y abrir el servidor es muy lento.

**Comment by sivicencio** [comment]
Hola Sergio,

¿Podrías incluir lo siguiente para tener más antecedentes?
- Un screenshot o log de la consola cuando ejecutas `yarn start`
- La versión de Node que estás utilizando (lo puedes ver con `node -v`)

**Comment by sgutgar** [comment]
Y probe con node 12.18.3 y 14.15.1

**Comment by sivicencio** [comment]
Recuerda adjuntar un screenshot o log de la consola, por favor. De lo contrario es difícil entender el error.

**Comment by sgutgar** [comment]
Me salió que había mandado una foto, voy de nuevo.
