### ISSUE TITLE
[Examen] Preguntas y respuestas (Q&A) sesión Zoom

### ISSUE THREAD

**Issue by sivicencio** [IIC2513-2020-2/syllabus#76]
Q: ¿El proyecto rehearsal tiene relación con el examen?
A: Son proyectos independientes, pero la configuración pueden reutlizarla (ej, la base de datos del backend puede ser la misma que utilicen para el examen)

Q: [Forma 1] Al final de Parte II, sección "Listado de comunas y sus pronósticos", dice "la información de cantidad de personas por días". ¿Está mal eso?
A: Efectivamente. Debiese ser "la información de pronósticos por día". Fue corregido el enunciado.

Q: ¿El formulario de ingreso de información debería incluir región?
A: No, ya que las regiones son sólo un dato (string) de las comunas. Se utilizan sólo para desplegar información, pero no se deben modificar

Q: En la Parte I, ¿el HTML debe incluir la información de los wireframes (regiones, comunas, datos)?
A: Sí, debe incluir al menos la misma información de los wireframes. Pueden agregar más datos si quieren para ver cómo se comporta el CSS, pero **en ningún caso deberían incluir menos datos**

Q: En la Parte III, ¿el formulario de login debería mostrar errores de validación?
A: No se aplicará validación de formularios en cliente (pero servidor sí puede responder con error y se debe mostrar un mensaje en este caso)

Q: ¿Debemos incluir la línea entre columnas que aparece en los wireframes?
A: Pueden omitir esta línea si quieren

Q: ¿Cómo deben ser los erorres en tercer endpoint (POST o PATCH dependiendo de forma)?
A: Si no se incluye información de autenticación (o no es válida) el endpoint debe retornar status code 401. Si hay algún error de validación, debe retornar status code 422. En el segundo endpoint (GET) sólo podría retornar 401 como error de autenticación (pero no 422 pues no se ingresa información, sino que sólo es de lectura)

Q: ¿Podemos utilizar packages libremente?
A: Sí, pueden utilizar los packages npm que quieran (esto, por supuesto, no incluye librerías CSS)

Q: Después de implementar la Parte I, ¿tenemos que borrar lo ya hecho al implementar la Parte III?
A: Deben reutilizar el CSS que ya escribieron, y el HTML convertirlo a componentes. Sin embargo, NO SE BORRA lo hecho en la Parte I, es decir, deben entregar los archivos en `src/static` (será evaluado). La idea es que reutilicen toda lo visual de la Parte I para escribir los componentes de la Parte III

Q: ¿Podemos utilizar librerías CSS como Bootstrap?
A: No, tienen que escribir el CSS ustedes

Q: ¿Cómo es la distribución de puntajes?
A: 2 puntos cada parte del examen (suman 6 en total)

Q: ¿Es legal googlear contenido? Si encuentro código que me sirva, ¿puedo utilizarlo?
A: Por supuesto, pueden googlear lo que quieran. En cuanto a código que encuentren y les sirva, deben referenciarlo en su entrega. Puede ser directamente incluyendo el link en un comentario JS en el código. En este caso, **DEBEN** incluir la referencia (sino es plagio)

Q: ¿Qué tan específica debe ser la paleta de colores para obtener el bono?
A: Debe ser coherente en cuanto a colores y estilos (todos los botones se ven similares, por ejemplo). La obtención del bono queda a criterio del ayudante corrector

Q: ¿Podemos utilizar los mismos estilos que en el proyecto del curso?
A: Sí, siempre que se respete lo que se puede ver en los wireframes (en cuanto a disposición y alineación de elementos)

Q: [Forma 1] En segundo endpoint (POST) de Parte II, ¿cómo obtener el parámetro de district?
A: El parámetro debe ser obtenido desde la URL (ejemplos de esto en proyecto savetalk, revisar definición de parámetros con `":"` y `router.param`)

Q: ¿Cómo debe funcionar la vista de login en una ventana menor a 501px?
A: Debe utilizar todo el ancho de la pantalla, en vez de dejar márgenes grandes

Q: ¿El formulario de login debe estar centrado verticalmente?
A: Sí. El enunciado fue actualizado con esta restricción

Q: [Forma 1] ¿Cómo debe funcionar la lista de `WeatherForecasts` ordenada?
A: Cada comuna tiene un campo `WeatherForecasts`, que es un array. Ese array debe entregarse por fecha en forma decreciente (de más reciente a más antiguo). El orden del array de comunas no tiene relevancia

**Comment by camaruri** [comment]
Se puede usar jsx?

**Comment by sivicencio** [comment]
Sí, pueden usarlo (y de hecho, el código base ya lo está usando).
