### ISSUE TITLE
Examen Forma 1 

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2513-2020-2/syllabus#77]
Para el HTML del contenido se muestran unas tablas, esta permitido usar <table> ? Porque creo que en el proyecto no se podía.

**Comment by meretamal** [comment]
Hola 😁 

Si puedes usar tablas. 

Para el proyecto, lo que no se podía era usar tablas para posicionar elementos, pero si es correcto usarlas para mostrar información.
