### ISSUE TITLE
Forma 3 - Parte II - Actualizar información

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2513-2020-2/syllabus#78]
Se nos pide actualizar la información del eclipse según la comuna. El id de la información es el mismo que el de districtId, lo cual quiero creer que es simple coincidencia debido al orden de las seeds, por lo que solo para confirmar: ¿debemos actualizar la información según el districtId y NO según el id de la información?

**Comment by sivicencio** [comment]
Tienes que actualizar la instancia de `EclipseInfo`, que tiene asociado un `districtId`. Debes efectivamente usar ese `districtId` para encontrar su información de eclipse asociada.

**Comment by VicenteElCyrano** [comment]
Gracias
