### ISSUE TITLE
Forma 1 - Listado de comunas y sus pronósticos - Orden por Regiones

### ISSUE THREAD

**Issue by humbertoortuzar** [IIC2513-2020-2/syllabus#79]
Hola! 
En el ejemplo de html del listado de weather forecasts, éstas están ordenadas según región.
![image](https://user-images.githubusercontent.com/53840891/102112699-d7767780-3e16-11eb-9659-76d2c43a604a.png)
Sin embargo, en el endpoint están en desorden y no se pide ordenarlas, por lo que me entró la duda de si debo efectivamente ordenar tipo:
Región --> Distrito --> Pronóstico
O si debe ser
Distrito --> Pronóstico
Para la parte 3 en React.

**Comment by sivicencio** [comment]
Hola Humberto,

Debes agrupar por región en el frontend. Efectivamente el listado que entrega el endpoint son comunas, pero tienen su campo `region`. Debes usar eso para agrupar en el lado del cliente.
