### ISSUE TITLE
Error en la bd al iniciar el template

### ISSUE THREAD

**Issue by crvargasu** [IIC2513-2020-2/syllabus#8]
Hola! Al instalé todas las dependencias según la clase de la parte 2 del template, pero al correr la app con yarn dev me sale el siguiente error

`Unable to connect to the database: ConnectionError [SequelizeConnectionError]: password authentication failed for user "cris"`

**Comment by crvargasu** [comment]
utilizo Ubuntu 20.04.1

**Comment by meretamal** [comment]
Hola 😁 

Por favor revisa [esta cápsula](https://github.com/IIC2513-2020-2/syllabus/blob/master/capsulas/capsula-01.md) que explica otra manera de hacer el _setup_ de tu base de datos y dime cómo te va 😉

**Comment by mimunoz11** [comment]
Hola, tenía el mismo problema y era porque direnv no estaba cargando las variables de entorno.
Con este comando me funcionó:
`echo 'eval "$(direnv hook bash)"' >> ~/.bashrc`
Luego:
`direnv allow`
Y finalmente 
`yarn dev`

**Comment by crvargasu** [comment]
Probé eso pero direnv sigue sin poder cargar las variables de entorno, ese es el problema, el archivo .envrc está en la carpeta principal de mi aplicación y la definí tal como mencionó el profesor en la capsula, sin embargo al hacer 
`echo $DB_USERNAME`
No me sale nada y por lo tanto, tampoco me funciona `yarn dev`

**Comment by meretamal** [comment]
Otra forma que te puede servir es creando un archivo **.env** en la raíz de tu app, escribir ahí tus variables de entorno y utilizar el paquete [dotenv](https://www.npmjs.com/package/dotenv) para leerlo

**Comment by crvargasu** [comment]
con dotenv funcionó, gracias!
