### ISSUE TITLE
Forma 1 - Parte II - Autentificacion

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2513-2020-2/syllabus#80]
Hola, no entiendo bien como proteger el endpoint, sin tener un usuario iniciado sesión (por que el inicio de sesión todavía no está implementado).Entiendo que hay que usar el endpoint que nos entrega las claves, pero no se a cual usuario 'consultar' sin tener ninguno que haya iniciado sesión.
Muchas gracias!

**Comment by sivicencio** [comment]
Tomás,

Planteas un buen punto. En las seeds puedes ver un usuario registrado que puedes usar para iniciar sesión. Lo dejaré acá de todas maneras (y lo agregaré al enunciado también):
```
E-email: user@example.org
Password: hola.123
```

**Comment by tomasalvarez13** [comment]
Entonces debo implementar el login antes de implementar la proteccion del endpoint? Eso es lo que no entiendo

**Comment by sivicencio** [comment]
El inicio de sesión (endpoint `/api/auth`) te entrega un JWT token. Ese token debes utilizarlo para autenticar a un usuario en futuros requests. No incluir el token es equivalente a no estar autenticado. La forma de incluirlo ya es parte de la evaluación y de la materia del curso.

**Comment by tomasalvarez13** [comment]
Es que mi pregunta es que mail y que password le entrego al endpoint `/api/auth` si por ahora no se puede iniciar sesión

**Comment by sivicencio** [comment]
Sí se puede iniciar sesión. El endpoint ya está implementado. Está en el enunciado explícito de hecho:

> El endpoint asociado a esto ya está implementado, mediante JSON Web Tokens (JWT), por lo que no debes modificar nada

Sólo tienes que hacer un request pasando las credenciales de prueba que puse anteriormente.

**Comment by tomasalvarez13** [comment]
Ok creo que entendí, gracias! Me estaba confundiendo con el log in de la parte 1, y con que no estaba implementado me referia a que no se podia iniciar sesion usandolo

**Comment by tomasalvarez13** [comment]
En el fondo con que me funcione desde postman solo si le entrego el token esta bien? Y si no lo entrego me tire error

Gracias

**Comment by sivicencio** [comment]
Exacto, con eso ya sabes que estás haciéndolo bien.
