### ISSUE TITLE
Forma 1 - parte 2 - ordenar por fecha

### ISSUE THREAD

**Issue by mvaldes12** [IIC2513-2020-2/syllabus#81]
Hola!

En la forma 1, parte 2 piden ordenar por fecha, pero según los datos ya está ordenado.
Puede ser un error ya que en la mañana esta forma en esta parte también tenía un error?

Quedo atenta
Gracias

**Comment by sivicencio** [comment]
El orden tiene que ser decreciente si te fijas en el enunciado. Lo que ves seguramente está en orden ascendente.

**Comment by sivicencio** [comment]
Y, aunque lo vieras ordenado de forma decreciente, el código implementado no incluye ese ordenamiento. Tiene que estar explícito.
