### ISSUE TITLE
Forma 3 Parte 1

### ISSUE THREAD

**Issue by aljara97** [IIC2513-2020-2/syllabus#82]
Hola, en la primera parte, para realizar el formulario de actualizar información no se especifica el tipo de input que debe ser el correspondiente a la altura del sol. Debe ser numérico también y de ser así tiene que permitir ingresar floats con alguna condición como en la duración?

**Comment by sivicencio** [comment]
Hola. Puede ser sólo de texto. No te preocupes por el formato (no se exige validación en este caso).

**Comment by aljara97** [comment]
Ok, muchas gracias :)
