### ISSUE TITLE
Examen Parte 1.2

### ISSUE THREAD

**Issue by martinrtc** [IIC2513-2020-2/syllabus#83]
Hola, no me queda muy claro exactamente que hay que implementar en esta parte, por lo que tengo entendido es puro "frontend", pero quiero saber si tiene que haber algúntipo de relación de los datos de la columna izquierda con los de la derecha, si al elegir una comuna al lado derecho tiene que aparecer la información de esa respectiva comuna o algo por el estilo, sineto que no queda muy claro en el enunciado. Ya que en mi forma (forma 3) la información de un lado coincide con la otra entonces se presta para pensar de que hay que implementar algo más.

**Comment by sivicencio** [comment]
El wireframe tiene como ejemplo los datos pre-llenados del form. En tu implementación de HTML de la Parte I no es necesario pre-llenar esto. No existe relación en el archivo HTML estático, pero eso está así en el wireframe porque en la Parte III **sí debes pre-llenar el formulario** al seleccionar una comuna con el primer campo (selector comuna).

**Comment by martinrtc** [comment]
Perfecto Muchas gracias
