### ISSUE TITLE
Forma 2 parte 2

### ISSUE THREAD

**Issue by faandrade** [IIC2513-2020-2/syllabus#84]
En el segundo endpoint "/api/districts/:id/influxes" se puede asumir que se van a ingresar fechas nuevas para cada district? o hay que controlar el caso en que se sobrescribe alguna fila en la base? (que por ejemplo, que se ingresen 2 veces alguna cantidad para un district y fecha)  o si pasa esto que simplemente queden las dos filas en la base haciendo referencia a la misma fecha y district?

**Comment by sivicencio** [comment]
Hola. No es necesario validar nada relacionado a las fechas, por lo que podrían quedar dos registros con la misma fecha. El enunciado se refiere precisamente a esto con las siguientes palabras (pero gracias por la pregunta porque tal vez no quedó tan claro):

> No es necesario validar uniqueness de fecha ni nada relacionado a fecha, pero sí debes validar que la cantidad de personas sea positiva

**Comment by faandrade** [comment]
No había leído esa parte :disappointed_relieved: .. otra cosa, en ese mismo punto, cuando envío una fecha en el formato YYYY-MM-DD en el content del request, una vez que se persiste en la base por alguna razón se le resta un día, por ejemplo si mando la fecha '2020-01-01' en la base después aparece como '2019-12-31', buscando en internet encontré que probablemente tenga que ver con el formato .. esto tiene alguna implicancia? (se me va a descontar por que suceda esto?)

**Comment by sivicencio** [comment]
No se va a descontar por estos detalles en las fechas. Probablemente es por diferencias de horarios en UTC (las fechas siempre son un tema). Si se envía la fecha en el formato indicado (`YYYY-MM-DD`) y se guarda en la base de datos, ya está bien.
