### ISSUE TITLE
Forma 2 parte 2 (ingresar cantidad de personas a una comuna)

### ISSUE THREAD

**Issue by mserranob** [IIC2513-2020-2/syllabus#86]
![image](https://user-images.githubusercontent.com/53835473/102119633-2ffe4280-3e20-11eb-9498-78740d8146b0.png)
Hola! ¿La validación es solo para los campos de los body parameters o también hay que comprobar que exista alguna comuna con el id entregado en el path?

**Comment by sivicencio** [comment]
Hola. Es sólo para los campos de body parameters. Si no existe la comuna, no será evaluado, pero si gustas, puedes retornar un error 404 en ese caso (pues significa que no existe una comuna con tal ID).
