### ISSUE TITLE
Forma 3 Parte 2 typo de dato de duration

### ISSUE THREAD

**Issue by bpeirano1** [IIC2513-2020-2/syllabus#87]
Hola quería saber si se puede asumir que en el request para actualizar el valor de las comunas el valor de duration va a ser siempre un numero o también tengo que preocuparme en el caso de que me den el numero cómo string?

Saludos

**Comment by sivicencio** [comment]
Hola. Puedes suponer que siempre será un número.

**Comment by bpeirano1** [comment]
ok gracias!
