### ISSUE TITLE
Forma 1 Parte 2 - Problema autenticación usuario

### ISSUE THREAD

**Issue by dpvillarroel** [IIC2513-2020-2/syllabus#88]
Hola!

Incluí todas las variables y rutas necesarias para hacer el endpoint que entrega la información de las comunas. De hecho pruebo el test sin autenticar usuario y funciona. 

El problema es cuando tengo que revisar si hay un usuario me sale  un `Authentication Error`  a pesar de estar pasándole el token a Postman. En consola me sale `Executing (default): SELECT count(*) AS "count" FROM "Users" AS "User`. Además cuando me meto a Postgres  a hacer un select de cualquier tabla me dice `relation "users" does not exist`, que podría ser?

**Comment by pwillmer** [comment]
Me pasa lo mismo!

**Comment by sivicencio** [comment]
En primera instancia no sé qué podría ser, y ahora estoy sin acceso a computador, pero puedo revisarlo en un rato más. Por ahora sí veo que ese mensaje de relation que no existe dice “users” con minúscula (la tabla es con mayúscula). No sé si eso te dé una pista.

**Comment by dpvillarroel** [comment]
Me pasa con cualquier tabla de la base de datos que dice que no existe

**Comment by jgramsch** [comment]
También me pasa

**Comment by dpvillarroel** [comment]
Efectivamente tenía que ver con la mayúscula! ahora me funciono gracias!

**Comment by sivicencio** [comment]
Ok, entonces ¿también pudiste hacer el request de las comunas con autenticación? ¿O ese era otro problema?

Y @jgramsch, lo que dijo @dpvillarroel ¿te da una pista o sigues con el error?

**Comment by sivicencio** [comment]
@pwillmer también tenías ese problema. ¿Tendrán que ver la mayúscula en tu caso también?

**Comment by jgramsch** [comment]
Emm a mi me pasa que en postgress se me cambia automáticamente a minusculas, al escribir `select * from Users;` en postgres me devuelve `relation "users" does not exist`.

**Comment by jgramsch** [comment]
me faltaban las comillas para seleccionar la tabla, aún así descubrí que mi problema es con las seed, las tablas no se llenan al hacer `yarn sequelize:seed`

**Comment by jgramsch** [comment]
resuelto, habia necesitaba hacer `seed:all`
