### ISSUE TITLE
Error con direnv allow para la parte 2 forma 2

### ISSUE THREAD

**Issue by fsmc** [IIC2513-2020-2/syllabus#89]
Estimad@: 

Al correr yarn dev y probar la ruta api/auth enviando un body en formato json, me aparece el siguiente error:
<img width="566" alt="Captura de pantalla 2020-12-14 a las 18 24 38" src="https://user-images.githubusercontent.com/53883295/102137594-d3a81c80-3e39-11eb-9295-418094622eea.png">

Este problema se asocia a que no se guardan las llaves secretas de mi archivo .envrc, ya que no me funciona el direnv allow.

Si me pudieran ayudar seria buenisimo ya que sino no puedo probar mis cambios.

Gracias!

**Comment by sivicencio** [comment]
Hola Francisco,

Si direnv no te funciona puedes correr la app con variables de ambiente directamente desde la consola de la siguiente forma:
```
DB_USERNAME=username DB_PASSWORD=password DB_NAME=db_name JWT_SECRET=some-secret yarn dev
```

Es decir, puedes colocar todas las variable como llave valor separadas por un espacio y finalmente el comando `yarn dev`.

**Comment by fsmc** [comment]
muchas gracias!!
