### ISSUE TITLE
[Actividades Clase 5] Duda almacenando valor retornado por arrow function 

### ISSUE THREAD

**Issue by MGome** [IIC2513-2020-2/syllabus#9]
Hola buenas,
Haciendo la actividad de la clase 5 (async js) me quedó una duda respecto a almacenar en una variable el resultado de una función que utiliza un Callback. En la primera parte se pide obtener los datos de los cursos para imprimirlos en un formato dado. El método para ejecutar las funciones que vienen creadas que utilicé fue el siguiente: 
![image](https://user-images.githubusercontent.com/48321270/94097272-99ac1900-fdfc-11ea-82c0-caf69ab4af24.png)
Sin embargo, al correrlo obtengo undefined como resultado: 
![image](https://user-images.githubusercontent.com/48321270/94097303-acbee900-fdfc-11ea-9787-9e86b784bece.png)
Probé haciendo un console log y se imprime sin problemas lo que está contenido en el parámetro "name". Pero al querer retornarlo no obtengo nada.

**Comment by sivicencio** [comment]
Hola @MGome

La función `getCourseNameWithCallback` (y las otras que terminan con `WithCallback`) no retorna el resultado (lo que implícitamente equivale a retornar `undefined`), sino que dentro del callback es donde debes trabajar para ir seteando la información de `courseInfo`. Para lograr imprimir el objeto `courseInfo` con toda la información requerida, tienes que asegurarte de que todos los callbacks fueron ejecutados, y la forma de hacer eso sería ir construyendo el objeto a medida que llamas "callback dentro de callback" (revisa el problema "Callback Hell", del que en este caso no puedes ni debes escapar).

En otras palabras, en el primer callback `(name) => name` deberías escribir más código que sólo retornar `name` (que en este caso no te está ayudando de hecho).

**Comment by MGome** [comment]
Oka! intentaré completar el callback. Muchas gracias!
