### ISSUE TITLE
Forma 3 Parte 2

### ISSUE THREAD

**Issue by vvcastro** [IIC2513-2020-2/syllabus#90]
Hola me queda una duda con la estructura que tiene el request.body en la parte del PATCH, se dice que:

> (...) además validar que todos los campos especificados en los body parameters no sean blancos, vacíos o nulos. Considera que podría suceder que sólo se quiera actualizar un campo solamente (no siempre todos a la vez).

Por lo que entiendo que se debe validar que **al menos 1 parámetro** sea no blanco, vacío o nulo, pero luego, en los casos especiales se dice que:

> Además debes exigir que los campos en el request body sean no vacíos

Mi duda sería si **se reciben todos los parámetros** y chequeo que uno no sea blanco, vacío o nulo o si **se reciben solo algunos** y de estos chequeo que sean todos no vacíos, blancos o nulos.

**Comment by sivicencio** [comment]
Hola. De los parámetros que sí están en el request body debes validar que sean no vacíos (sería lo último que dices, si entendí bien).
