### ISSUE TITLE
Forma 1 Parte 3

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2513-2020-2/syllabus#91]
Hola, estoy teniendo el siguiente error al tratar de consumir la api desde react. Algun consejo de que podria ser?

![image](https://user-images.githubusercontent.com/48598610/102139305-6fd32300-3e3c-11eb-9b39-ff2a9924882f.png)

**Comment by sivicencio** [comment]
Tiene que ver precisamente con los CORS (lo vimos al final del curso).
