### ISSUE TITLE
Submit formulario

### ISSUE THREAD

**Issue by camaruri** [IIC2513-2020-2/syllabus#92]
Hola, estoy teniendo problemas con enviar el formulario en la parte III forma 1
No puedo enviar desde el login los datos porque me sale este error
<img width="1548" alt="Captura de Pantalla 2020-12-14 a la(s) 19 18 24" src="https://user-images.githubusercontent.com/53882047/102142418-246f4380-3e41-11eb-8f4d-645e4fe136e6.png">
se cae justo cuando hace el post a la api de localhose:3000/api/auth

**Comment by sivicencio** [comment]
Depende de cómo estás enviando los datos probablemente. ¿Esto te da una idea? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

**Comment by camaruri** [comment]
Cuando hago console log del data que voy cambiando con el componente de react me sale esto:
 {email: SyntheticBaseEvent, password: SyntheticBaseEvent}

<img width="982" alt="Captura de Pantalla 2020-12-14 a la(s) 21 36 11" src="https://user-images.githubusercontent.com/53882047/102152733-65248800-3e54-11eb-8313-de0339516e72.png">

No entiendo bien que es SyntheticBaseEvent, ni como capturarlo
Nose si sera un error en como mandar la informacion o como recibirla y pasarla para hacer el request a la API
Muchas gracias

**Comment by sivicencio** [comment]
Lo que veo es que estás asignando a `email` y `password` el `event` que se dispara (probablemente) al ocurrir `onChange`. Tienes que obtener el valor a partir de ese evento: `event.target.value`.

**Comment by camaruri** [comment]
Todavia no me sale, tendria que cambiar la forma en que estoy haciendo el form y submit?
Porque cuando veo lo que esta en event.target.value solo me sale el ultimo caracter que ingrese.
He leido harto la documentacion y todavia no se donde me estoy equivocando
