### ISSUE TITLE
Forma 1 Parte 2 ID

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2513-2020-2/syllabus#93]
Hola, estoy creando el objeto WeatherForecast para guardarlo en la base de datos, pero al hacer build con la funcion del ORM me retorna todo bien pero un id nulo (que debo retornar despues en el response). Debo cambiar algo en el modelo? o estoy haciendo algo mal?
Edit: el id se genera despues del save, gracias de todas formas je.

**Comment by sivicencio** [comment]
Hola, te dejo una pista: `save` es asíncrono.
