### ISSUE TITLE
parte 3

### ISSUE THREAD

**Issue by martinrtc** [IIC2513-2020-2/syllabus#94]
hola tengo una duda sobre la parte 3, sale que tenemos que traducir el archivo login.html, debemos cambiarlo completamente a react? como nos van a revisar la parte 1 siesque es asi?

**Comment by sivicencio** [comment]
La parte 1 se entrega en los archivos en la carpeta `src/static`. Los componentes en React estarán en otro lugar (serán otros archivos dentro de `src`). No deben cambiar lo que corresponde a la parte 1, sino que usarlo de base para implementar componentes.
