### ISSUE TITLE
parte 3 HTML no funciona en React al hacer iteraciones

### ISSUE THREAD

**Issue by crvargasu** [IIC2513-2020-2/syllabus#95]
Hola, he estado con un problema constante, que es que al realizar map o iteraciones a listas, html no funciona con esos valores, a pesar que al hacerle console.log si funcionan.

Por ejemplo, lo siguiente
`<option value="1">{comuna[0]}</option>`
            `<option value="1">{comuna[1]}</option>`
           ` <option value="1">{comuna[2]}</option>`
              `{`
                `comuna.map(c => {`
                    `<option value="1">{c}</option>`
                `})`
             ` }`
Para insertar valores a un dropdown, las opciones del principio si funcionan, pero la segunda no funciona al realizar el map.

Me pasa muy seguido, no sé por qué html deja de imprimir en las iteraciones

**Comment by sivicencio** [comment]
Hola. Te falta retornar dentro de la función que le pasas a map. Si no retornas algo de esa función, no pasará nada.
