### ISSUE TITLE
Tarea rematch

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2513-2020-2/syllabus#96]
Hola, que estaba haciendo la tarea, y empezé por copiar lo del principio del tutorial de rematch para probar que todo funcione y al poner lo primero que se hace en el tutorial: 
![Captura de pantalla de 2020-12-18 11-18-25](https://user-images.githubusercontent.com/53836282/102624432-c6817b00-4122-11eb-8dbd-49ad6d0fe218.png)

Obtengo el siguiente error:
![Captura de pantalla de 2020-12-18 11-18-56](https://user-images.githubusercontent.com/53836282/102624494-db5e0e80-4122-11eb-9cfb-afcc7fb67824.png)
Pero como simplemente copié lo que se hizo, nosé que hacer

**Comment by ariela1** [comment]
A mi me paso lo mismo, pero me funcionó al ponerla dentro de una función asíncrona

**Comment by Pdesolmi** [comment]
Buena gracias!, y no te pasa que tienes algunas veces números distintos a los del enunciado en las posiciones?, como [73863,74013) en vez de [73743,73893). O te dan todos perfecto?, porque revisé y según yo estoy bien.

**Comment by jjaubele** [comment]
La página de Chile en wikipedia fue editada ayer 17 de diciembre a las 11:48, así que las consultas del enunciado están con una versión anterior y por eso da distinto según yo.

**Comment by Pdesolmi** [comment]
Gracias!, además para la consulta numero 4 See Also y External links también deberían estar incluidas según yo, ya que no tienen subtítulos

**Comment by sivicencio** [comment]
Hola, disculpen lo tarde. El equipo desarrollador de la tarea nos comunicó que para la consulta 4 el resultado esperado realmente es:
```
Título: 'Etymology' - Contenido: [2519,3855)
Título: 'See also' - Contenido: [78713,78792)
Título: 'Further reading' - Contenido: [78869,78871)
Título: 'External links' - Contenido: [78892,79342)
```

Se considerará esto en la corrección.
