### ISSUE TITLE
TAREA REMATCH 2

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2513-2020-2/syllabus#97]
Hola!, que tengo 2 dudas, la primera es si alguien me puede ayudar a como correr la tarea en mi computador, o como instalaron wikijs. Y la otra, que los numeros del Contenido siento que pueden variar dependiendo si uno incluye los \n o no dentro de la variable, y siento que es dificil saber cual es la forma exacta de hacerlo.

**Comment by ariela1** [comment]
Creo que es un poco tarde, pero para instalar wikijs utilice `npm install wikijs`, [](https://www.npmjs.com/package/wikijs?spm=a2c6h.14275010.0.0.5f2b669dmHWUH2). En cuanto a la segunda estoy igual, solo intente llegar lo mas cerca que pude a la solución del enunciado
