### ISSUE TITLE
Problema formulario Rematch

### ISSUE THREAD

**Issue by ariela1** [IIC2513-2020-2/syllabus#98]
Holaa! Al tratar de subir el archivo en el formulario es como si no hubiera subido nada, traté de enviarlo por gmail a mi misma para probar desde otro computador y me salió un mensaje de bloqueado por motivos de seguridad, por ello asumo que debe ser un problema con la extensión del archivo que google no permite subir. Alguien más que este con el mismo problema o que le haya pasado?

**Comment by meretamal** [comment]
Hola 😁 

En ese caso suban un .zip

**Comment by ariela1** [comment]
gracias!
