### ISSUE TITLE
Tarea Rematch

### ISSUE THREAD

**Issue by tomidubost** [IIC2513-2020-2/syllabus#99]
Hola! tengo una duda respecto del formato de entrega. En las consultas 4, 5 y 6 antes de la parte que dice contenido hay dos espacios. Lo agregamos así en el out.txt o lo dejamos con un espacio como las tres primeras consultas. Pregunto esto puesto que se corrige tipo test. Saludos.

**Comment by MaximilianoVergara** [comment]
tengo la misma duda
